language: node_js
sudo: required
node_js:
  - '5.0.0'
before_install:
  - apt-get update
  - apt-get install gcc-4.8 g++-4.8
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
before_script:
  - npm install -g gulp
script: gulp