language: node_js
sudo: required
node_js:
  - '5.0.0'
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8 --force-yes
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
before_script:
  - npm install -g gulp
  - npm install -g karma
script: gulp